version: 2

updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - "SEU-USUARIO-GITHUB"
    labels:
      - "dependencies"
      - "python"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - "SEU-USUARIO-GITHUB"
    labels:
      - "dependencies"
      - "docker"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - assignees:
  - "FabianaCampanari"
    labels:
      - "dependencies"
      - "github-actions"
