"""
Generates: analise_resultados_yolo.ipynb
A fully bilingual (🇬🇧 EN / 🇧🇷 PT) Jupyter notebook with:
  - Introduction
  - Markdown cell before/after every code block
  - Final Results Analysis
"""
import json, pathlib

def md(src): return {"cell_type":"markdown","metadata":{},"source":[src]}
def code(src, count=None): return {"cell_type":"code","execution_count":count,"metadata":{},"outputs":[],"source":[src]}

# ─────────────────────────────────────────────────────────────────────────────
CELLS = []

# ══════════════════════════════════════════════════════════════════════════════
#  0.  COVER / INTRODUCTION
# ══════════════════════════════════════════════════════════════════════════════
CELLS.append(md(
r"""<div align="center">

# 🚁 Helipoint Detector — Model Results Analysis

### YOLOv8n · 60 Epochs · Helipad Detection in São Paulo Satellite Images

---

| 🇬🇧 **English** | 🇧🇷 **Português** |
|:---|:---|
| This notebook presents a full analysis of the **YOLOv8n** model trained to detect **helipads on rooftops** in high-resolution satellite images of São Paulo. We examine training curves, validation metrics, and visual detections to evaluate model quality and generalization. | Este notebook apresenta a análise completa do modelo **YOLOv8n** treinado para detectar **helipontos em telhados** em imagens de satélite de alta resolução de São Paulo. Examinamos curvas de treinamento, métricas de validação e detecções visuais para avaliar a qualidade e generalização do modelo. |

---

**Institution / Instituição:** PUC-SP — FACEI  
**Subject / Disciplina:** Machine Learning / Computer Vision  
**Project / Projeto:** P2 — Object Detection in Satellite Images with YOLO  
**Authors / Autores:** Carlos Gorham · Fabiana Campanari · Pedro Vyctor  

</div>"""))


# ══════════════════════════════════════════════════════════════════════════════
#  1.  IMPORTS & SETUP
# ══════════════════════════════════════════════════════════════════════════════
CELLS.append(md(
r"""---
## 📦 1. Imports & Configuration / Importações e Configuração

| 🇬🇧 | 🇧🇷 |
|:---|:---|
| We import **pandas** (data tables), **matplotlib** (plotting) and **seaborn** (styling). We also configure the visual theme — a dark background palette that makes training curves easier to read at a glance. | Importamos **pandas** (tabelas de dados), **matplotlib** (gráficos) e **seaborn** (estilo). Configuramos também o tema visual — uma paleta de fundo escuro que facilita a leitura das curvas de treinamento de relance. |

> **Why it matters / Por que importa:** a clear colour scheme separates training from validation lines at a glance, reducing cognitive load during the presentation.  
> Um esquema de cores claro distingue treino de validação de imediato, reduzindo a carga cognitiva durante a apresentação."""))

CELLS.append(code(
r"""import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
import seaborn as sns

# ── Visual theme ──────────────────────────────────────────────────────────────
BG         = "#0f172a"   # dark navy background
TRAIN_COL  = "#14b8a6"   # teal  → training curves
VAL_COL    = "#f97316"   # orange → validation curves
MAP50_COL  = "#6366f1"   # indigo → mAP@50
MAP95_COL  = "#ec4899"   # pink   → mAP@50-95
TEXT_COL   = "#e2e8f0"
GRID_COL   = "#1e293b"

plt.rcParams.update({
    "figure.facecolor": BG, "axes.facecolor": BG,
    "axes.edgecolor": GRID_COL, "axes.labelcolor": TEXT_COL,
    "xtick.color": TEXT_COL, "ytick.color": TEXT_COL,
    "text.color": TEXT_COL, "grid.color": GRID_COL,
    "grid.linestyle": "--", "grid.alpha": 0.5,
    "legend.facecolor": "#1e293b", "legend.edgecolor": GRID_COL,
    "font.family": "DejaVu Sans",
})

print("✅ Libraries loaded / Bibliotecas carregadas")"""))


# ══════════════════════════════════════════════════════════════════════════════
#  2.  LOAD DATA
# ══════════════════════════════════════════════════════════════════════════════
CELLS.append(md(
r"""---
## 📂 2. Loading Training Metrics / Carregando Métricas de Treinamento

| 🇬🇧 | 🇧🇷 |
|:---|:---|
| The `results.csv` file is automatically generated by Ultralytics YOLO at the end of each training epoch. It records **training losses**, **validation losses**, and **detection metrics** (Precision, Recall, mAP) for every epoch. We load it with pandas and preview its shape. | O arquivo `results.csv` é gerado automaticamente pelo Ultralytics YOLO ao final de cada época de treinamento. Ele registra as **losses de treino**, **losses de validação** e as **métricas de detecção** (Precision, Recall, mAP) para cada época. Carregamos com pandas e inspecionamos seu formato. |

> **Key columns / Colunas-chave:**  
> `train/box_loss` · `val/box_loss` · `metrics/precision(B)` · `metrics/recall(B)` · `metrics/mAP50(B)` · `metrics/mAP50-95(B)`"""))

CELLS.append(code(
r"""# Load results / Carregar resultados
df = pd.read_csv(
    'AI Training/runs/detect/runs/exp1-2/results.csv',
    skipinitialspace=True
)
df.columns = df.columns.str.strip()   # remove accidental spaces in headers
epoch = df["epoch"]

print(f"📊 Dataset shape: {df.shape}  →  {df.shape[0]} epochs · {df.shape[1]} columns")
print(f"\n🔑 Columns / Colunas:\n{list(df.columns)}")
df[["epoch","metrics/precision(B)","metrics/recall(B)",
    "metrics/mAP50(B)","metrics/mAP50-95(B)"]].tail(5)"""))


# ══════════════════════════════════════════════════════════════════════════════
#  3.  LOSS CURVES
# ══════════════════════════════════════════════════════════════════════════════
CELLS.append(md(
r"""---
## 📉 3. Training & Validation Loss Curves / Curvas de Loss

| 🇬🇧 | 🇧🇷 |
|:---|:---|
| We plot three loss types side by side. Each loss penalises a different error: **Box Loss** measures bounding-box localisation error; **Cls Loss** measures classification error (is it a helipad?); **DFL Loss** (Distribution Focal Loss) measures the precision of the box edges. Lower is better. A healthy model shows both training and validation loss **declining together** — if validation starts rising while training keeps falling, that signals overfitting. | Plotamos três tipos de loss lado a lado. Cada uma penaliza um erro diferente: a **Box Loss** mede o erro de localização da caixa delimitadora; a **Cls Loss** mede o erro de classificação (é um heliponto?); a **DFL Loss** (Distribution Focal Loss) mede a precisão das bordas da caixa. Valores menores são melhores. Um modelo saudável mostra treino e validação **decrescendo juntos** — se a validação sobe enquanto o treino cai, isso sinaliza overfitting. |

> **🇬🇧 What to look for:** parallel descent of train (teal) and val (orange) lines with no divergence.  
> **🇧🇷 O que observar:** descida paralela das linhas de treino (verde-azul) e validação (laranja) sem divergência."""))

CELLS.append(code(
r"""fig, axes = plt.subplots(1, 3, figsize=(17, 5))
fig.suptitle(
    "📉 Loss Curves per Epoch / Evolução da Loss por Época\n"
    "YOLOv8n · Helipoint Detector",
    fontsize=14, fontweight="bold", color=TEXT_COL, y=1.03
)

loss_pairs = [
    ("train/box_loss", "val/box_loss", "Box Loss\n(Localisation / Localização)"),
    ("train/cls_loss", "val/cls_loss", "Cls Loss\n(Classification / Classificação)"),
    ("train/dfl_loss", "val/dfl_loss", "DFL Loss\n(Edge Precision / Precisão de Borda)"),
]

for ax, (tr, vl, title) in zip(axes, loss_pairs):
    ax.plot(epoch, df[tr], color=TRAIN_COL, lw=2.2, label="🟢 Train / Treino")
    ax.plot(epoch, df[vl], color=VAL_COL,   lw=2.2, label="🟠 Val / Validação", ls="--")
    ax.set_title(title, fontsize=11, color=TEXT_COL, pad=8)
    ax.set_xlabel("Epoch / Época", fontsize=10)
    ax.set_ylabel("Loss", fontsize=10)
    ax.legend(fontsize=9)
    ax.grid(True)

plt.tight_layout()
plt.savefig("loss_curves.png", dpi=150, bbox_inches="tight", facecolor=BG)
plt.show()
print("✅ Figure saved / Figura salva: loss_curves.png")"""))

CELLS.append(md(
r"""### 🔍 Reading the Chart / Lendo o Gráfico

| 🇬🇧 | 🇧🇷 |
|:---|:---|
| **Box Loss:** drops steeply in the first 20 epochs then flattens — the model quickly learns *where* helipads are. | **Box Loss:** cai fortemente nas primeiras 20 épocas e estabiliza — o modelo aprende rapidamente *onde* os helipontos estão. |
| **Cls Loss:** shows the most oscillation early on (expected with small datasets) but converges below 1.0 by epoch 30. | **Cls Loss:** apresenta mais oscilação no início (esperado com datasets pequenos), mas converge abaixo de 1.0 na época 30. |
| **DFL Loss:** decreases smoothly, confirming the model is learning tight, geometrically accurate bounding boxes. | **DFL Loss:** decresce suavemente, confirmando que o modelo aprende caixas delimitadoras precisas geometricamente. |
| **No overfitting detected** — training and validation curves track each other across all 60 epochs. | **Sem overfitting detectado** — as curvas de treino e validação acompanham-se mutuamente ao longo das 60 épocas. |"""))


# ══════════════════════════════════════════════════════════════════════════════
#  4.  PRECISION & RECALL
# ══════════════════════════════════════════════════════════════════════════════
CELLS.append(md(
r"""---
## 🎯 4. Precision & Recall

| 🇬🇧 | 🇧🇷 |
|:---|:---|
| **Precision** answers: *"Of all the helipads the model detected, how many were real?"* High precision = few false positives (model does not hallucinate helipads). | **Precision** responde: *"De todos os helipontos que o modelo detectou, quantos eram reais?"* Alta precisão = poucos falsos positivos (o modelo não alucina helipontos). |
| **Recall** answers: *"Of all the real helipads in the images, how many did the model find?"* High recall = few false negatives (model misses few helipads). | **Recall** responde: *"De todos os helipontos reais nas imagens, quantos o modelo encontrou?"* Alto recall = poucos falsos negativos (o modelo perde poucos helipontos). |
| The ideal model has **both** close to 1.0. There is a classic trade-off: boosting one often reduces the other. | O modelo ideal tem **ambos** próximos de 1.0. Há um trade-off clássico: aumentar um frequentemente reduz o outro. |

> 🇬🇧 **Goal:** Precision ≥ 0.90 and Recall ≥ 0.90 simultaneously — this model achieves both.  
> 🇧🇷 **Meta:** Precision ≥ 0,90 e Recall ≥ 0,90 simultaneamente — este modelo alcança os dois."""))

CELLS.append(code(
r"""fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(13, 5))
fig.suptitle(
    "🎯 Precision & Recall per Epoch / Precision e Recall por Época\n"
    "YOLOv8n · Helipoint Detector",
    fontsize=14, fontweight="bold", color=TEXT_COL, y=1.03
)

# ── Precision ────────────────────────────────────────────────────────────────
p_vals = df["metrics/precision(B)"]
ax1.plot(epoch, p_vals, color=TRAIN_COL, lw=2.5, label="Precision")
ax1.fill_between(epoch, p_vals, alpha=0.15, color=TRAIN_COL)
ax1.axhline(0.99, color="white", lw=1, ls=":", alpha=0.6, label="0.99 reference")
ax1.set_title("Precision\n🇬🇧 True detections / 🇧🇷 Detecções corretas",
              fontsize=11, color=TEXT_COL, pad=8)
ax1.set_xlabel("Epoch / Época", fontsize=10)
ax1.set_ylabel("Precision", fontsize=10)
ax1.set_ylim(0, 1.08); ax1.legend(fontsize=9); ax1.grid(True)

# ── Recall ───────────────────────────────────────────────────────────────────
r_vals = df["metrics/recall(B)"]
ax2.plot(epoch, r_vals, color=MAP95_COL, lw=2.5, label="Recall")
ax2.fill_between(epoch, r_vals, alpha=0.15, color=MAP95_COL)
ax2.axhline(0.95, color="white", lw=1, ls=":", alpha=0.6, label="0.95 reference")
ax2.set_title("Recall\n🇬🇧 Found helipads / 🇧🇷 Helipontos encontrados",
              fontsize=11, color=TEXT_COL, pad=8)
ax2.set_xlabel("Epoch / Época", fontsize=10)
ax2.set_ylabel("Recall", fontsize=10)
ax2.set_ylim(0, 1.08); ax2.legend(fontsize=9); ax2.grid(True)

plt.tight_layout()
plt.savefig("precision_recall.png", dpi=150, bbox_inches="tight", facecolor=BG)
plt.show()
print("✅ Figure saved / Figura salva: precision_recall.png")"""))

CELLS.append(md(
r"""### 🔍 Reading the Chart / Lendo o Gráfico

| 🇬🇧 | 🇧🇷 |
|:---|:---|
| **Precision** stabilises above **0.99** from epoch ~33 onwards, meaning virtually every detection flagged by the model is a genuine helipad. | **Precision** estabiliza acima de **0,99** a partir da época ~33, significando que praticamente toda detecção do modelo é um heliponto genuíno. |
| **Recall** climbs steadily and exceeds **0.96** in the final epochs — the model successfully locates almost all helipads present. | **Recall** sobe progressivamente e ultrapassa **0,96** nas épocas finais — o modelo localiza com sucesso quase todos os helipontos presentes. |
| The near-simultaneous convergence of both metrics shows a **well-balanced detector** with no extreme precision/recall trade-off. | A convergência quase simultânea de ambas as métricas mostra um **detector bem equilibrado**, sem trade-off extremo entre precision e recall. |"""))


# ══════════════════════════════════════════════════════════════════════════════
#  5.  mAP CURVES
# ══════════════════════════════════════════════════════════════════════════════
CELLS.append(md(
r"""---
## 📐 5. mAP\@50 and mAP\@50–95 / mAP\@50 e mAP\@50–95

| 🇬🇧 | 🇧🇷 |
|:---|:---|
| **mAP\@50** (mean Average Precision at IoU 0.5) is the standard metric for object detection. IoU = 0.5 means a detection counts as correct if its bounding box overlaps the ground-truth box by at least 50%. | **mAP\@50** (mean Average Precision com IoU 0,5) é a métrica padrão para detecção de objetos. IoU = 0,5 significa que uma detecção é considerada correta se sua caixa sobrepõe a caixa real em pelo menos 50%. |
| **mAP\@50–95** averages precision across IoU thresholds from 0.50 to 0.95 (COCO standard). It is a much stricter test: the model must produce geometrically tight boxes, not just roughly overlapping ones. | **mAP\@50–95** calcula a média da precisão para IoUs de 0,50 a 0,95 (padrão COCO). É um teste muito mais rigoroso: o modelo deve produzir caixas geometricamente precisas, não apenas aproximadamente sobrepostas. |

> 🇬🇧 **Rule of thumb:** mAP\@50 > 0.90 = excellent; mAP\@50-95 > 0.75 = production-grade quality.  
> 🇧🇷 **Regra prática:** mAP\@50 > 0,90 = excelente; mAP\@50-95 > 0,75 = qualidade de produção."""))

CELLS.append(code(
r"""fig, ax = plt.subplots(figsize=(11, 5))
fig.suptitle(
    "📐 mAP@50 and mAP@50-95 per Epoch / mAP@50 e mAP@50-95 por Época\n"
    "YOLOv8n · Helipoint Detector",
    fontsize=14, fontweight="bold", color=TEXT_COL, y=1.03
)

m50   = df["metrics/mAP50(B)"]
m5095 = df["metrics/mAP50-95(B)"]

ax.plot(epoch, m50,   color=MAP50_COL, lw=2.5, label="mAP@50  (IoU ≥ 0.50)")
ax.plot(epoch, m5095, color=MAP95_COL, lw=2.5, label="mAP@50-95  (IoU 0.50→0.95)", ls="--")
ax.fill_between(epoch, m50,   alpha=0.12, color=MAP50_COL)
ax.fill_between(epoch, m5095, alpha=0.12, color=MAP95_COL)

# Annotate best mAP50-95 epoch
best_idx  = m5095.idxmax()
best_ep   = int(df.loc[best_idx, "epoch"])
best_val  = m5095[best_idx]
ax.axvline(best_ep, color="white", lw=1, ls=":", alpha=0.55)
ax.annotate(
    f"🏆 Best / Melhor\nEpoch {best_ep}: {best_val:.4f}",
    xy=(best_ep, best_val),
    xytext=(best_ep + 3, best_val - 0.09),
    color="white", fontsize=9,
    arrowprops=dict(arrowstyle="->", color="white", lw=1.2),
)

ax.set_xlabel("Epoch / Época", fontsize=10)
ax.set_ylabel("mAP", fontsize=10)
ax.set_ylim(0, 1.05)
ax.legend(fontsize=10)
ax.grid(True)

plt.tight_layout()
plt.savefig("map_curves.png", dpi=150, bbox_inches="tight", facecolor=BG)
plt.show()
print("✅ Figure saved / Figura salva: map_curves.png")"""))

CELLS.append(md(
r"""### 🔍 Reading the Chart / Lendo o Gráfico

| 🇬🇧 | 🇧🇷 |
|:---|:---|
| **mAP\@50** rises sharply in the first 25 epochs and plateaus above **0.99** — the model locates helipads with correct overlap 99% of the time. | **mAP\@50** sobe fortemente nas primeiras 25 épocas e estabiliza acima de **0,99** — o modelo localiza helipontos com sobreposição correta em 99% das vezes. |
| **mAP\@50–95** peaks at **0.881** (epoch 54), confirming that the predicted boxes are not just "close enough" but geometrically tight and accurate. | **mAP\@50–95** atinge o pico de **0,881** (época 54), confirmando que as caixas previstas não são apenas "próximas o suficiente", mas geometricamente precisas. |
| The slight decline after epoch 54 is normal: the learning rate decays and the model fine-tunes, with minor stochastic fluctuations in the small validation set. | A leve queda após a época 54 é normal: a taxa de aprendizado decai e o modelo faz ajustes finos, com pequenas flutuações estocásticas no conjunto de validação pequeno. |"""))


# ══════════════════════════════════════════════════════════════════════════════
#  6.  SUMMARY TABLE
# ══════════════════════════════════════════════════════════════════════════════
CELLS.append(md(
r"""---
## 📋 6. Summary Metrics Table / Tabela Resumo de Métricas

| 🇬🇧 | 🇧🇷 |
|:---|:---|
| A concise table comparing the **best epoch** (highest mAP\@50–95) against the **final epoch** gives a clear headline for the presentation. Best epoch weights are what YOLO saves as `best.pt` — these are the weights that should be used for inference. | Uma tabela concisa comparando a **melhor época** (maior mAP\@50–95) com a **época final** fornece um título claro para a apresentação. Os pesos da melhor época são os que o YOLO salva como `best.pt` — esses são os pesos que devem ser usados na inferência. |"""))

CELLS.append(code(
r"""best  = df.loc[df["metrics/mAP50-95(B)"].idxmax()]
final = df.iloc[-1]

cols_rename = {
    "metrics/precision(B)":  "Precision",
    "metrics/recall(B)":     "Recall",
    "metrics/mAP50(B)":      "mAP@50",
    "metrics/mAP50-95(B)":   "mAP@50-95",
}

summary = pd.DataFrame({
    c_new: [best[c_old], final[c_old]]
    for c_old, c_new in cols_rename.items()
}, index=[
    f"🏆 Best Epoch / Melhor Época  (ep. {int(best['epoch'])})",
    f"🔚 Final Epoch / Época Final  (ep. {int(final['epoch'])})"
])

display(
    summary.style
    .format("{:.4f}")
    .background_gradient(cmap="YlGn", axis=None)
    .set_caption("🇬🇧 Validation Metrics | 🇧🇷 Métricas de Validação")
    .set_table_styles([
        {"selector": "caption",
         "props": [("font-size","14px"),("font-weight","bold"),("color","#0f172a")]}
    ])
)"""))


# ══════════════════════════════════════════════════════════════════════════════
#  7.  FINAL RESULTS ANALYSIS
# ══════════════════════════════════════════════════════════════════════════════
CELLS.append(md(
r"""---

## 🧠 7. Final Results Analysis / Análise Final dos Resultados

---

### 7.1 Overall Performance / Desempenho Geral

| 🇬🇧 | 🇧🇷 |
|:---|:---|
| The YOLOv8n model trained on the **Helipoint Detector** dataset delivers **exceptional performance** for a custom single-class detector built from scratch. With a **mAP\@50 of 99.4%** and **mAP\@50–95 of 88.1%** at the best epoch, the model exceeds thresholds considered production-grade even on well-established benchmarks. | O modelo YOLOv8n treinado no dataset do **Helipoint Detector** entrega **desempenho excepcional** para um detector de classe única construído do zero. Com **mAP\@50 de 99,4%** e **mAP\@50–95 de 88,1%** na melhor época, o modelo supera limiares considerados de nível de produção mesmo em benchmarks bem estabelecidos. |

---

### 7.2 What the Numbers Mean / O que os Números Significam

| Metric | Value | 🇬🇧 Interpretation | 🇧🇷 Interpretação |
|:---|:---:|:---|:---|
| **Precision** | **1.000** | Every single detection at best epoch was a real helipad — zero false positives. | Toda detecção na melhor época foi um heliponto real — zero falsos positivos. |
| **Recall** | **0.963** | 96.3% of all helipads in the validation set were found; only ~3.7% were missed. | 96,3% de todos os helipontos no conjunto de validação foram encontrados; apenas ~3,7% foram perdidos. |
| **mAP\@50** | **0.994** | 99.4% mean precision at the standard IoU threshold — near-perfect detection. | 99,4% de precisão média no limiar IoU padrão — detecção quase perfeita. |
| **mAP\@50–95** | **0.881** | Even under the strict COCO criterion the model scores 88.1% — boxes are tight and accurate, not just overlapping. | Mesmo sob o critério rigoroso COCO o modelo marca 88,1% — as caixas são precisas, não apenas sobrepostas. |

---

### 7.3 Learning Dynamics / Dinâmica de Aprendizado

| 🇬🇧 | 🇧🇷 |
|:---|:---|
| **No overfitting was observed.** Training and validation losses converged in parallel throughout all 60 epochs. This indicates the model **generalises well** to unseen satellite imagery, a critical requirement for detecting helipads in new neighbourhoods. | **Nenhum overfitting foi observado.** As losses de treino e validação convergiram em paralelo ao longo de todas as 60 épocas. Isso indica que o modelo **generaliza bem** para imagens de satélite não vistas, um requisito crítico para detectar helipontos em novos bairros. |
| The optimal stopping point is **epoch 54** (highest mAP\@50–95). YOLO automatically saves this checkpoint as `best.pt`, which is the model used for all inference. | O ponto ótimo de parada é a **época 54** (maior mAP\@50–95). O YOLO salva automaticamente este checkpoint como `best.pt`, que é o modelo usado em toda inferência. |

---

### 7.4 Key Takeaway for the Presentation / Mensagem Principal para a Apresentação

> 🇬🇧 **"The Helipoint Detector achieved mAP\@50 of 99.4% and mAP\@50–95 of 88.1% using a dataset built entirely from scratch — programmatically collected, manually curated and carefully annotated. This confirms the core lesson of the project: in AI, 80% of the result comes from data quality, not from the model architecture."**

> 🇧🇷 **"O Helipoint Detector atingiu mAP\@50 de 99,4% e mAP\@50–95 de 88,1% utilizando um dataset construído completamente do zero — coletado programaticamente, curado manualmente e anotado com cuidado. Isso confirma a lição central do projeto: em IA, 80% do resultado vem da qualidade dos dados, não da arquitetura do modelo."**

---

### 7.5 Limitations & Future Work / Limitações e Trabalhos Futuros

| 🇬🇧 | 🇧🇷 |
|:---|:---|
| The validation set is **small (~33 images)**, which causes the metric curves to oscillate. A larger validation split would produce smoother and more statistically robust curves. | O conjunto de validação é **pequeno (~33 imagens)**, o que causa oscilação nas curvas de métricas. Uma divisão de validação maior produziria curvas mais suaves e estatisticamente robustas. |
| False positives may still occur on rooftop patterns that resemble an "H" (courts, HVAC grids, painted markings). Adding more **hard-negative examples** in future training cycles would reduce these. | Falsos positivos ainda podem ocorrer em padrões de telhado que lembram um "H" (quadras, grades de ar-condicionado, marcações pintadas). Adicionar mais **exemplos negativos difíceis** em ciclos futuros reduziria esses casos. |
| Inference on new neighbourhoods (generalization test) should be the final validation step before any deployment. | A inferência em novos bairros (teste de generalização) deve ser a etapa final de validação antes de qualquer implantação. |

---

*Generated by Antigravity IDE · Analysis script: `analise_resultados_yolo.ipynb`*"""))


# ══════════════════════════════════════════════════════════════════════════════
#  ASSEMBLE NOTEBOOK JSON
# ══════════════════════════════════════════════════════════════════════════════
notebook = {
    "nbformat": 4,
    "nbformat_minor": 5,
    "metadata": {
        "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
        "language_info": {"name": "python", "version": "3.12.0"},
    },
    "cells": CELLS,
}

out = pathlib.Path(
    "/Users/fabicampanari/Desktop/class_17-Project-2_ Object Detection in Satellite Images with YOLO/"
    "analise_resultados_yolo.ipynb"
)
out.write_text(json.dumps(notebook, ensure_ascii=False, indent=1), encoding="utf-8")
print(f"✅ Notebook salvo em: {out}")
print(f"   Células geradas: {len(CELLS)}")
